[0m18:55:20.911282 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a621624730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a620755660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a620755600>]}


============================== 18:55:20.913077 | 269c543e-5963-4c27-a44c-453d8e138b7b ==============================
[0m18:55:20.913077 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:55:20.913478 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/ravindug/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:55:20.917632 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/ravindug/.dbt')}
[0m18:55:20.917926 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:55:47.672129 [debug] [MainThread]: Starter project path: /home/ravindug/Projects/DBT_Snowflake/dbt_env/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:55:47.674055 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:55:47.674558 [info ] [MainThread]: Setting up your profile.
[0m18:58:31.108578 [info ] [MainThread]: Profile data_pipeline written to /home/ravindug/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:58:31.151267 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 190.27591, "process_in_blocks": "40", "process_kernel_time": 0.067117, "process_mem_max_rss": "104564", "process_out_blocks": "88", "process_user_time": 0.998256}
[0m18:58:31.152806 [debug] [MainThread]: Command `dbt init` succeeded at 18:58:31.152528 after 190.28 seconds
[0m18:58:31.153803 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a621624730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a620755750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x71a620755630>]}
[0m18:58:31.154501 [debug] [MainThread]: Flushing usage events
[0m18:58:32.465438 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:01:07.639658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762c13dc820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762c078d750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762c078d6c0>]}


============================== 19:01:07.641665 | 415c2842-7631-4578-8fc8-b15286bdcade ==============================
[0m19:01:07.641665 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:01:07.642193 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/ravindug/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:01:07.647012 [info ] [MainThread]: dbt version: 1.9.3
[0m19:01:07.647316 [info ] [MainThread]: python version: 3.10.12
[0m19:01:07.647589 [info ] [MainThread]: python path: /home/ravindug/Projects/DBT_Snowflake/dbt_env/bin/python3
[0m19:01:07.647830 [info ] [MainThread]: os info: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
[0m19:01:07.774639 [info ] [MainThread]: Using profiles dir at /home/ravindug/.dbt
[0m19:01:07.775053 [info ] [MainThread]: Using profiles.yml file at /home/ravindug/.dbt/profiles.yml
[0m19:01:07.775377 [info ] [MainThread]: Using dbt_project.yml file at /home/ravindug/Projects/DBT_Snowflake/dbt_project.yml
[0m19:01:07.775773 [info ] [MainThread]: adapter type: snowflake
[0m19:01:07.776036 [info ] [MainThread]: adapter version: 1.9.2
[0m19:01:07.776296 [info ] [MainThread]: Configuration:
[0m19:01:07.776521 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m19:01:07.776743 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:01:07.776970 [info ] [MainThread]: Required dependencies:
[0m19:01:07.777220 [debug] [MainThread]: Executing "git --help"
[0m19:01:07.780037 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:01:07.780384 [debug] [MainThread]: STDERR: "b''"
[0m19:01:07.780626 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:01:07.780878 [info ] [MainThread]: Connection:
[0m19:01:07.781117 [info ] [MainThread]:   account: https://jj29623.australia-east.azure.snowflakecomputing.com
[0m19:01:07.781351 [info ] [MainThread]:   user: ragwap
[0m19:01:07.781594 [info ] [MainThread]:   database: dbt_db
[0m19:01:07.781831 [info ] [MainThread]:   warehouse: dbt_wh
[0m19:01:07.782055 [info ] [MainThread]:   role: dbt_role
[0m19:01:07.782289 [info ] [MainThread]:   schema: dbt_schema
[0m19:01:07.782510 [info ] [MainThread]:   authenticator: None
[0m19:01:07.782729 [info ] [MainThread]:   oauth_client_id: None
[0m19:01:07.782947 [info ] [MainThread]:   query_tag: None
[0m19:01:07.783167 [info ] [MainThread]:   client_session_keep_alive: False
[0m19:01:07.783411 [info ] [MainThread]:   host: None
[0m19:01:07.783634 [info ] [MainThread]:   port: None
[0m19:01:07.783856 [info ] [MainThread]:   proxy_host: None
[0m19:01:07.784078 [info ] [MainThread]:   proxy_port: None
[0m19:01:07.784307 [info ] [MainThread]:   protocol: None
[0m19:01:07.784532 [info ] [MainThread]:   connect_retries: 1
[0m19:01:07.784755 [info ] [MainThread]:   connect_timeout: None
[0m19:01:07.784978 [info ] [MainThread]:   retry_on_database_errors: False
[0m19:01:07.785206 [info ] [MainThread]:   retry_all: False
[0m19:01:07.785431 [info ] [MainThread]:   insecure_mode: False
[0m19:01:07.785655 [info ] [MainThread]:   reuse_connections: True
[0m19:01:07.785986 [info ] [MainThread]: Registered adapter: snowflake=1.9.2
[0m19:01:07.911293 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m19:01:07.928841 [debug] [MainThread]: Using snowflake connection "debug"
[0m19:01:07.929301 [debug] [MainThread]: On debug: select 1 as id
[0m19:01:07.929568 [debug] [MainThread]: Opening a new connection, currently in state init
[0m19:02:34.027468 [debug] [MainThread]: Snowflake adapter: Error running SQL: select 1 as id
[0m19:02:34.028768 [debug] [MainThread]: Snowflake adapter: Rolling back transaction.
[0m19:02:34.029443 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m19:02:34.029999 [info ] [MainThread]: [31m2 checks failed:[0m
[0m19:02:34.030357 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/ravindug/Projects/DBT_Snowflake/dbt_project.yml> not found

[0m19:02:34.030652 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m19:02:34.032939 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 86.42974, "process_in_blocks": "48", "process_kernel_time": 0.12812, "process_mem_max_rss": "112768", "process_out_blocks": "40", "process_user_time": 1.114047}
[0m19:02:34.034996 [debug] [MainThread]: Command `dbt debug` failed at 19:02:34.034847 after 86.43 seconds
[0m19:02:34.035491 [debug] [MainThread]: Connection 'debug' was left open.
[0m19:02:34.035980 [debug] [MainThread]: On debug: No close available on handle
[0m19:02:34.036492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762c13dc820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762c078d600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7762bee6fd60>]}
[0m19:02:34.037117 [debug] [MainThread]: Flushing usage events
[0m19:02:35.569443 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:07:59.119824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420e528730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420d589690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420d589630>]}


============================== 19:07:59.121649 | bca4e414-91ad-46ff-9423-cd2036b0a5ef ==============================
[0m19:07:59.121649 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:07:59.122057 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/ravindug/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:07:59.122530 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ravindug/Projects/DBT_Snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:07:59.123167 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.03998749, "process_in_blocks": "0", "process_kernel_time": 0.064044, "process_mem_max_rss": "87412", "process_out_blocks": "16", "process_user_time": 0.871608}
[0m19:07:59.123515 [debug] [MainThread]: Command `dbt deps` failed at 19:07:59.123443 after 0.04 seconds
[0m19:07:59.123852 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420e528730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420d589840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72420d5898d0>]}
[0m19:07:59.124138 [debug] [MainThread]: Flushing usage events
[0m19:08:15.335217 [debug] [MainThread]: An error was encountered while trying to flush usage events
